CREATE TABLE Governorate
(
  GID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (GID),
  UNIQUE (Name)
);

CREATE TABLE University
(
  UID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Phone number VARCHAR(15) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  Website VARCHAR(50) NOT NULL,
  GID INT NOT NULL,
  PRIMARY KEY (UID),
  FOREIGN KEY (GID) REFERENCES Governorate(GID),
  UNIQUE (Name)
);

CREATE TABLE Faculty
(
  FID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Phone number VARCHAR(15) NOT NULL,
  Address VARCHAR(100) NOT NULL,
  Website VARCHAR(50) NOT NULL,
  Description VARCHAR(150) NOT NULL,
  Admission conditions VARCHAR(150) NOT NULL,
  UID INT NOT NULL,
  PRIMARY KEY (FID),
  FOREIGN KEY (UID) REFERENCES University(UID),
  UNIQUE (Name)
);

CREATE TABLE Department
(
  Name VARCHAR(50) NOT NULL,
  DID INT NOT NULL,
  Description VARCHAR(150) NOT NULL,
  Admission conditions VARCHAR(150) NOT NULL,
  FID INT NOT NULL,
  PRIMARY KEY (DID),
  FOREIGN KEY (FID) REFERENCES Faculty(FID),
  UNIQUE (Name)
);
